#### Week 9 Lecture (Session 6) Python nltk for Sentiment Analysis
<author>&copy; Professor Yuefeng Li </authors>

### NLTK Sentiment Analysis

In [3]:
# You may need to install nltk

# !pip install nltk

In [5]:
import nltk
# first time only
# nltk.download('all')

In [6]:
# import libraries
import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [9]:
# Load the amazon review dataset

df = pd.read_csv('https://raw.githubusercontent.com/pycaret/pycaret/master/datasets/amazon.csv')
#df = pd.read_csv('amazon.csv')
df

                                              reviewText  Positive
0      This is a one of the best apps acording to a b...         1
1      This is a pretty good version of the game for ...         1
2      this is a really cool game. there are a bunch ...         1
3      This is a silly game and can be frustrating, b...         1
4      This is a terrific game on any pad. Hrs of fun...         1
...                                                  ...       ...
19995  this app is fricken stupid.it froze on the kin...         0
19996  Please add me!!!!! I need neighbors! Ginger101...         1
19997  love it!  this game. is awesome. wish it had m...         1
19998  I love love love this app on my side of fashio...         1
19999  This game is a rip off. Here is a list of thin...         0

[20000 rows x 2 columns]

In [11]:
# Define a function parse_text function for text pre-processing
def parse_text(text):
    # Tokenize the text
    tokens = word_tokenize(text.lower())
    # Remove stop words
    filtered_tokens = [token for token in tokens if token not in stopwords.words('english')]
    # Lemmatize the tokens (like stemming but it brings context to the words, and links words with similar meanings to one word)
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in filtered_tokens]

    # Join the tokens back into a string
    processed_text = ' '.join(lemmatized_tokens)
    return processed_text

In [13]:
# apply the parse_text function via df
df['reviewText'] = df['reviewText'].apply(parse_text)
df

                                              reviewText  Positive
0      one best apps acording bunch people agree bomb...         1
1      pretty good version game free . lot different ...         1
2      really cool game . bunch level find golden egg...         1
3      silly game frustrating , lot fun definitely re...         1
4      terrific game pad . hr fun . grandkids love . ...         1
...                                                  ...       ...
19995  app fricken stupid.it froze kindle wont allow ...         0
19996  please add ! ! ! ! ! need neighbor ! ginger101...         1
19997  love ! game . awesome . wish free stuff house ...         1
19998  love love love app side fashion story fight wo...         1
19999  game rip . list thing make better & bull ; fir...         0

[20000 rows x 2 columns]

In [14]:
# initialize NLTK sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

# Define cal_sentiment_scor() function, which uses polarity_scores() to obtain a dictionary of 
#  sentiment scores ([-1, +1]) for positive, negative or neutral sentiments.
# The polarity is then determined by checking whether the positive score is greater than a threshold theta,  
#  then returns a sentiment score of 1 if it is, and a 0 otherwise (a binary decison making). 

def cal_sentiment_score(text):
    theta = 0.15 # a threshold 
    scores = analyzer.polarity_scores(text)
    sentiment = 1 if scores['pos'] > theta else 0
    return sentiment

# apply get_sentiment function
df['sentiment'] = df['reviewText'].apply(cal_sentiment_score)

df

                                              reviewText  Positive  sentiment
0      one best apps acording bunch people agree bomb...         1          1
1      pretty good version game free . lot different ...         1          1
2      really cool game . bunch level find golden egg...         1          1
3      silly game frustrating , lot fun definitely re...         1          1
4      terrific game pad . hr fun . grandkids love . ...         1          1
...                                                  ...       ...        ...
19995  app fricken stupid.it froze kindle wont allow ...         0          0
19996  please add ! ! ! ! ! need neighbor ! ginger101...         1          1
19997  love ! game . awesome . wish free stuff house ...         1          1
19998  love love love app side fashion story fight wo...         1          1
19999  game rip . list thing make better & bull ; fir...         0          1

[20000 rows x 3 columns]

In [17]:
# Evaluate the proposed get_sentiment() function by comparing two columns 'Positive' and 'sentiment' 
from sklearn.metrics import confusion_matrix
print(confusion_matrix(df['Positive'], df['sentiment']))

from sklearn.metrics import classification_report
print(classification_report(df['Positive'], df['sentiment']))

[[ 2059  2708]
 [ 1545 13688]]
              precision    recall  f1-score   support

           0       0.57      0.43      0.49      4767
           1       0.83      0.90      0.87     15233

    accuracy                           0.79     20000
   macro avg       0.70      0.67      0.68     20000
weighted avg       0.77      0.79      0.78     20000